name: Core
version: 1.0
main: ca.bungo.core.core.Core
softdepend: [Vault]
commands:
  rank:
    usage: /rank <player> <rank>
  stats:
    usage: /stats
  name:
    usage: /name <name>
  nick:
    usage: /nick
  sban:
    usage: /sban <player> <time> <reason>
  gban:
    usage: /gban <player> <time> <reason>
  kick:
    usage: /kick <player> <reason>
  exp:
    usage: /exp <player> <add/set/remove> <amount>
  creload:
    usage: /creload
    aliases: [rl,crl,reload]
  gm:
    usage: /gm
    aliases: [gamemode,gmc,gms,gma,gmsp]
