name: Core
version: 1.0
main: ca.bungo.main.Core
commands:
  rank:
    usage: /rank <player> <rank>
  info:
    usage: /info
  name:
    usage: /name <name>
  nick:
    usage: /nick
  sban:
    usage: /sban <player> <time> <reason>